import express from "express";
import cors from "cors";
import fs from "node:fs";
import path from "node:path";
import pc from "picocolors";
import routes from "./routes/index.js";
import { startTunnel, stopTunnel } from "./tunnel/ngrok.js";
import { getActiveProject, resetActiveProject } from "./services/projects.js";
import { initProject } from "./commands/init.js";
import { logger } from "./utils/logger.js";
import { getEnv } from "./utils/env.js";
import { findAvailablePort } from "./utils/ports.js";
import { printBox } from "./utils/box.js";
import { isApprovalRequired } from "./services/approval.js";
import { getOwnerPassword, isAutoGeneratedPassword } from "./services/oauth.js";

import { fileURLToPath } from "node:url";

export const app = express();

app.use(
  cors({
    origin: "*",
    exposedHeaders: ["Mcp-Session-Id", "Mcp-Protocol-Version"],
    allowedHeaders: [
      "Content-Type",
      "mcp-session-id",
      "mcp-protocol-version",
      "last-event-id",
      "ngrok-skip-browser-warning",
      "Authorization",
    ],
  }),
);

app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(routes);

export let tunnelListener = null;
export let httpServer = null;
export let PORT = 4173;
let tunnelMonitorGeneration = 0;
let tunnelReconnectTimer = null;

/** All active sockets — tracked so they can be destroyed immediately on shutdown */
const openSockets = new Set();

function scheduleTunnelReconnect(port, generation) {
  tunnelReconnectTimer = setTimeout(async () => {
    tunnelReconnectTimer = null;
    if (isShuttingDown || generation !== tunnelMonitorGeneration) return;

    try {
      const replacement = await startTunnel(port);
      if (replacement) {
        tunnelListener = replacement;
        logger.tunnelInfo("Tunnel reconnected.");
        monitorTunnel(port, replacement);
        return;
      }
    } catch (err) {
      logger.tunnelError("Tunnel reconnect attempt failed", err);
    }

    scheduleTunnelReconnect(port, generation);
  }, 1000);
  tunnelReconnectTimer.unref?.();
}

function monitorTunnel(port, listener) {
  const generation = ++tunnelMonitorGeneration;

  listener
    .join()
    .catch((err) => {
      logger.tunnelError("ngrok tunnel stopped unexpectedly", err);
    })
    .finally(() => {
      if (isShuttingDown || generation !== tunnelMonitorGeneration) return;

      logger.tunnelWarn("Tunnel disconnected. Reconnecting automatically...");
      scheduleTunnelReconnect(port, generation);
    });
}

export async function startServer(options = {}) {
  const requestedPort =
    parseInt(options.port || getEnv("PORT", 4173), 10) || 4173;
  PORT = await findAvailablePort(requestedPort);

  if (PORT !== requestedPort) {
    logger.serverWarn(
      `Port ${requestedPort} is currently occupied. Automatically switched to port ${PORT}.`,
    );
  }

  return new Promise((resolve, reject) => {
    httpServer = app.listen(PORT, async (err) => {
      if (err) return reject(err);

      // MCP uses long-lived streaming requests. Node's defaults can terminate
      // an otherwise healthy tunnel while no JSON-RPC request is in flight.
      httpServer.requestTimeout = 0;
      httpServer.timeout = 0;
      httpServer.keepAliveTimeout = 120_000;
      httpServer.headersTimeout = 125_000;

      httpServer.on("connection", (socket) => {
        openSockets.add(socket);
        socket.on("close", () => openSockets.delete(socket));
      });

      const projectRoot = path.resolve(getEnv("PROJECT_ROOT", "."));
      const configPath = path.join(projectRoot, "codemcp.json");

      if (!fs.existsSync(configPath)) {
        await initProject(projectRoot, { yes: true, silent: true });
        resetActiveProject();
      }

      const project = getActiveProject();
      tunnelListener = await startTunnel(PORT);
      if (tunnelListener) {
        monitorTunnel(PORT, tunnelListener);
      }

      const globalUrl = tunnelListener
        ? `${typeof tunnelListener.url === "function" ? tunnelListener.url() : tunnelListener.url}/mcp`
        : `http://localhost:${PORT}/mcp`;

      const permissionText =
        project.permission === "both"
          ? pc.green("Read & Write")
          : project.permission === "write"
            ? pc.yellow("Write-only")
            : pc.cyan("Read-only");

      const title = pc.bold(
        pc.bgCyan(pc.black(" CodeMCP Project Agent (MCP) ")),
      );
      const rows = [
        `${pc.bold("Project    :")} ${pc.green(project.name)} ${pc.dim(`(${project.id})`)}`,
        `${pc.bold("Root       :")} ${pc.dim(project.root)}`,
        `${pc.bold("Config     :")} ${
          project.configFile
            ? pc.green(path.basename(project.configFile))
            : pc.yellow("(auto-generated)")
        }`,
        `${pc.bold("Permission :")} ${permissionText}`,
        `${pc.bold("Approval   :")} ${
          isApprovalRequired(project, "WRITE")
            ? pc.yellow("Enabled (Ask before changes)")
            : pc.dim("Disabled (Auto-apply)")
        }`,
        `${pc.bold("Context    :")} ${
          project.contextFile ? pc.white(project.contextFile) : pc.dim("(none)")
        }`,

        `${pc.bold("Password   :")} ${
          isAutoGeneratedPassword()
            ? `${pc.bold(pc.yellow(getOwnerPassword()))} ${pc.dim("(auto-generated, saved to vault)")}`
            : pc.green("Configured via OWNER_PASSWORD")
        }`,
        `${pc.bold("Local URL  :")} ${pc.cyan(`http://localhost:${PORT}/mcp`)}`,
        `${pc.bold("Global URL :")} ${pc.bold(pc.magenta(globalUrl))}`,
      ];

      printBox(title, rows);
      console.log(
        pc.dim(
          "  Waiting for AI client requests... (tool activity appears below)\n",
        ),
      );

      resolve({ app, httpServer, port: PORT });
    });
  });
}

let isShuttingDown = false;

export function resetShutdownState() {
  isShuttingDown = false;
}

export async function handleShutdown(signal = "SIGINT") {
  if (isShuttingDown) {
    // Immediate termination on second Ctrl+C
    process.exit(130);
  }
  isShuttingDown = true;
  tunnelMonitorGeneration++;
  if (tunnelReconnectTimer) {
    clearTimeout(tunnelReconnectTimer);
    tunnelReconnectTimer = null;
  }

  logger.serverInfo(`Received ${signal} — shutting down...`);

  // Hard safety timeout — guarantees process termination within 1.5s even if any network cleanup hangs
  const forceExit = setTimeout(() => {
    logger.serverWarn("Forced shutdown after timeout.");
    process.exit(0);
  }, 1500);
  if (typeof forceExit.unref === "function") {
    forceExit.unref();
  }

  // 1. Immediately destroy all active sockets (SSE streams, MCP keep-alives) so httpServer.close() won't hang
  for (const socket of openSockets) {
    try {
      socket.destroy();
    } catch {}
  }
  openSockets.clear();

  // 2. Shut down HTTP server and tunnel in parallel
  const shutdownTasks = [];

  if (httpServer) {
    if (typeof httpServer.closeAllConnections === "function") {
      try {
        httpServer.closeAllConnections();
      } catch {}
    }
    shutdownTasks.push(
      new Promise((resolve) => {
        try {
          httpServer.close(() => {
            logger.serverInfo("HTTP server closed.");
            resolve();
          });
        } catch {
          resolve();
        }
      }),
    );
  }

  if (tunnelListener) {
    shutdownTasks.push(
      stopTunnel(tunnelListener).catch((err) => {
        logger.tunnelError("Error closing tunnel during shutdown", err);
      }),
    );
  }

  try {
    await Promise.race([
      Promise.all(shutdownTasks),
      new Promise((resolve) => setTimeout(resolve, 1000)),
    ]);
  } catch {}

  clearTimeout(forceExit);
  process.exit(0);
}

let handlersRegistered = false;

export function setupShutdownHandlers() {
  if (handlersRegistered) return;
  handlersRegistered = true;

  process.on("SIGINT", () => handleShutdown("SIGINT"));
  process.on("SIGTERM", () => handleShutdown("SIGTERM"));
  process.on("SIGHUP", () => handleShutdown("SIGHUP"));
  if (process.platform === "win32") {
    process.on("SIGBREAK", () => handleShutdown("SIGBREAK"));
  }
}

setupShutdownHandlers();

// Auto-start if executed directly (e.g. node src/server.js)
const isDirectExecution =
  process.argv[1] &&
  (fileURLToPath(import.meta.url) === path.resolve(process.argv[1]) ||
    process.argv[1].endsWith("src/server.js") ||
    process.argv[1].endsWith("src\\server.js"));

if (isDirectExecution) {
  startServer().catch((err) => {
    logger.error(`Failed to start server: ${err.message}`);
    process.exit(1);
  });
}

export default app;
