import fs from "node:fs/promises";
import path from "node:path";
import { z } from "zod";
import { PathGuardError, toPosix } from "../utils/pathGuard.js";
import { logger } from "../utils/logger.js";
import {
  verifyActionApproval,
  isApprovalRequired,
} from "../services/approval.js";
import { recordAction } from "../services/memory.js";
import {
  createToolContext,
  wrapToolHandler,
  formatToolResponse,
} from "./context.js";

/**
 * Registers the `delete_file` tool with the MCP server.
 * Removes a file safely from the project directory, enforcing path boundary restrictions,
 * sensitive file blacklists, and interactive human verification.
 *
 * @param {import("@modelcontextprotocol/sdk/server/mcp.js").McpServer | import("./context.js").ToolContext} serverOrCtx - The MCP server instance or shared tool context
 * @param {object} [project] - The scoped project definition (if server instance provided directly)
 */
export function registerDeleteFileTool(serverOrCtx, project) {
  const ctx = serverOrCtx?.guard
    ? serverOrCtx
    : createToolContext(serverOrCtx, project);
  const { server: mcpServer, guard } = ctx;

  mcpServer.registerTool(
    "delete_file",
    {
      description:
        "Deletes a file within the project folder. Use with caution for refactoring or cleanup.",
      inputSchema: {
        path: z
          .string()
          .describe(
            "File path relative to project root to delete, e.g. temp.js",
          ),
        summary: z
          .string()
          .optional()
          .describe(
            "A concise 1-sentence explanation generated by the AI assistant explaining why this file is being deleted or what it was",
          ),
      },
    },
    wrapToolHandler("DELETE", async (args) => {
      const relPath = args?.path;
      if (!relPath || typeof relPath !== "string" || !relPath.trim()) {
        throw new PathGuardError("Path is required", 400);
      }

      const cleanRelPath = relPath.trim();
      const absolutePath = guard.resolveSafe(cleanRelPath);

      if (guard.isProtectedFromDeletion(absolutePath)) {
        // Silently skip protected configuration files without throwing error or logging BLOCKED
        return {
          content: [
            {
              type: "text",
              text: `Skipped protected file "${cleanRelPath}".`,
            },
          ],
        };
      }

      if (guard.isIgnored(absolutePath)) {
        throw new PathGuardError(
          "Deleting this file is blocked (protected or sensitive)",
          403,
        );
      }

      let stat;
      try {
        stat = await fs.stat(absolutePath);
      } catch (err) {
        if (err.code === "ENOENT") {
          throw new PathGuardError("File not found", 404);
        }
        throw new PathGuardError(`Unable to access file: ${err.message}`, 500);
      }

      if (!stat.isFile()) {
        throw new PathGuardError("Path is a directory, not a file", 400);
      }

      const normalized = toPosix(cleanRelPath);

      // Interactive approval check if configured
      if (isApprovalRequired(ctx.project, "DELETE")) {
        logger.toolDeletePending(normalized);
      }

      const approvalResult = await verifyActionApproval({
        project: ctx.project,
        actionType: "DELETE",
        path: normalized,
        size: stat.size,
        logger,
      });

      if (!approvalResult.approved) {
        return approvalResult.rejectionResponse;
      }

      await fs.unlink(absolutePath);
      const message = `Successfully deleted ${normalized}`;

      const sizeFormatted =
        stat.size > 1024
          ? `${(stat.size / 1024).toFixed(1)} KB`
          : `${stat.size} B`;
      const aiSummary = args?.summary?.trim() || args?.reason?.trim();
      const finalSummary =
        aiSummary || `Deleted ${path.basename(normalized)} (${sizeFormatted})`;

      logger.toolDelete(normalized);
      recordAction(ctx.project || ctx.projectRoot, {
        action: "DELETE",
        target: normalized,
        client: logger.getActiveClient(),
        details: `Deleted ${sizeFormatted}`,
        summary: finalSummary,
      }).catch(() => {});

      return formatToolResponse(
        {
          success: true,
          path: normalized,
          message,
        },
        message,
      );
    }),
  );
}
